<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629268136796' stop='1629268343930'>
    <name>verify log project append funtion</name>
    <title>verify log project append funtion</title>
    <test-cases>
        <test-case start='1629268136796' status='passed' stop='1629268139619'>
            <name>Qick append verify add new line</name>
            <title>Qick append verify add new line</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1629268139619' status='passed' stop='1629268140814'>
            <name>Qick append verify delete new line</name>
            <title>Qick append verify delete new line</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1629268140815' status='failed' stop='1629268142155'>
            <name>Qick append verify upload sigle log file and publish</name>
            <title>Qick append verify upload sigle log file and publish</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='981ad1a0-5afc-4f0d-b1f0-b518e14adb5d-attachment.png' type='image/png' size='41964'/>
            </attachments>
            <failure>
                <message>ElementNotVisibleError: element not interactable
                  (Session info: chrome=92.0.4515.131)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)</message>
                <stack-trace>ElementNotVisibleError: element not interactable
                  (Session info: chrome=92.0.4515.131)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)
                    at Object.checkLegacyResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\error.js:546:15)
                    at parseHttpResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:509:13)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:441:30
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)
                From: Task: WebElement.clear()
                    at Driver.schedule (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at WebElement.schedule_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
                    at WebElement.clear (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2351:17)
                    at actionFn (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:89:44)
                    at Array.map (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:461:65
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27Error: 
                    at ElementArrayFinder.applyAction_ (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as clear] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as clear] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:831:22)
                    at CommonAppend.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\general\common-append.ts:73:34)
                    at Generator.next (&lt;anonymous>)
                    at fulfilled (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:112:62)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629268142155' status='failed' stop='1629268343927'>
            <name>File append verify selete existing log file</name>
            <title>File append verify selete existing log file</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='ee60ac91-be41-4e14-b50a-c22ed2122329-attachment.png' type='image/png' size='89592'/>
                <attachment title='Screenshot' source='d486e680-1942-4db2-b25c-75ebebce7c1d-attachment.png' type='image/png' size='89592'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (internal/timers.js:554:17)
                    at processTimers (internal/timers.js:497:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>