<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629692701120' stop='1629693102812'>
    <name>verify generate-download-share funtion verify community-dataset tab</name>
    <title>verify generate-download-share funtion verify community-dataset tab</title>
    <test-cases>
        <test-case start='1629692701121' status='failed' stop='1629692902548'>
            <name>Generate-new-dataset</name>
            <title>Generate-new-dataset</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='a668d454-3a24-449f-9f91-d229833a1faf-attachment.png' type='image/png' size='59232'/>
                <attachment title='Screenshot' source='5bb70d69-7880-4491-9d92-aa3cbebd8327-attachment.png' type='image/png' size='59232'/>
            </attachments>
            <failure>
                <message>WebDriverError: element click intercepted: Element &lt;a _ngcontent-oyg-c1="" class="nav-link" href="/datasets" routerlinkactive="active">...&lt;/a> is not clickable at point (580, 30). Other element would receive the click: &lt;div _ngcontent-oyg-c13="" class="modal">...&lt;/div>
                  (Session info: chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)</message>
                <stack-trace>WebDriverError: element click intercepted: Element &lt;a _ngcontent-oyg-c1="" class="nav-link" href="/datasets" routerlinkactive="active">...&lt;/a> is not clickable at point (580, 30). Other element would receive the click: &lt;div _ngcontent-oyg-c13="" class="modal">...&lt;/div>
                  (Session info: chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)
                    at Object.checkLegacyResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\error.js:546:15)
                    at parseHttpResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:509:13)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:441:30
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                From: Task: WebElement.click()
                    at Driver.schedule (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at WebElement.schedule_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
                    at WebElement.click (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
                    at actionFn (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:89:44)
                    at Array.map (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:461:65
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27Error: 
                    at ElementArrayFinder.applyAction_ (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:831:22)
                    at Function.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\utils\function-util.ts:127:15)
                    at Generator.next (&lt;anonymous>)
                    at fulfilled (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:112:62)
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629692902548' status='failed' stop='1629693102809'>
            <name>Download project</name>
            <title>Download project</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='fd641ef1-17c6-46fb-bda6-7a4f62a19315-attachment.png' type='image/png' size='59232'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>